#17: Added rendering for aggregate functions `GROUPING` and `APPROXIMATE COUNT DISTINCT`
exasol/virtual-schema-common-lua pull request #49
Opened 2022-08-25 13:50 UTC by redcatbear

Closes #17.

2022-08-25 18:20 UTC, tomuben commented on spec/queryrenderer/literal_constructors.lua
> +-- @param ... list of Lua literals and or tables
```suggestion
-- @param ... list of Lua literals and/or tables
```

2022-08-25 18:24 UTC, tomuben reviewed
just a tiny suggestion

2022-08-26 05:46 UTC, kaklakariada requested changes

2022-08-26 05:46 UTC, kaklakariada commented on doc/changes/changes_2.2.0.md
> +* #47: Removed dependency check CI build
This is not done in this PR?

2022-08-26 05:46 UTC, kaklakariada commented on spec/QueryRenderer_spec.lua
> +                            tableName ="T2"
```suggestion
                            tableName = "T2"
```

2022-08-26 05:46 UTC, kaklakariada commented on spec/queryrenderer/AggregateFunctionAppender_spec.lua
> +function it_asserts(expected, actual, explanation)
Global function by intention?
```suggestion
local function it_asserts(expected, actual, explanation)
```

2022-08-26 06:04 UTC, kaklakariada submitted a review, later dismissed

2022-08-26 06:22 UTC, kaklakariada approved these changes

2022-08-26 06:23 UTC, merged