#57: Support `GROUP BY`
exasol/virtual-schema-common-lua pull request #58
Opened 2022-09-30 11:44 UTC by redcatbear

Closes #57.

2022-09-30 13:16 UTC, kaklakariada requested changes

2022-09-30 13:16 UTC, kaklakariada commented on src/exasolvs/queryrenderer/SelectAppender.lua
> +    ExpressionAppender:new(self._out_query):append_expression(expression)
👍

2022-09-30 13:16 UTC, kaklakariada commented on spec/queryrenderer/SelectAppender_spec.lua
> +        assert_yields('SELECT COUNT(*), "TICKETS"."TYPE" FROM "TICKETS" GROUP BY "TICKETS"."TYPE"', original_query)
Add a test with multiple group by items to check that the comma is added

2022-10-04 05:28 UTC, redcatbear commented
Done.

2022-10-04 06:23 UTC, kaklakariada approved these changes

2022-10-04 09:07 UTC, merged