Refactoring/7 add missing abstract methods
exasol/virtual-schema-common-lua pull request #8
Opened 2022-03-28 11:41 UTC by redcatbear

Closes #7.

This PR grew a bit out of proportion since I realized that the properties should be mainly handled by this base library to avoid code duplication.

2022-03-29 05:06 UTC, kaklakariada requested changes

2022-03-29 05:06 UTC, kaklakariada commented on spec/AbstractVirtualSchemaAdapter_spec.lua
> +                {type = "getCapabilities", capabilities={"cap1", "cap2"}})
```suggestion
        assert.are.same(vs_adapter:get_capabilities(nil, properties),
                {type = "getCapabilities", capabilities={"cap1", "cap2"}})
```

2022-03-29 05:06 UTC, kaklakariada commented on spec/AdapterProperties_spec.lua
> +                    .. ", but got 'host:no-a-number' instead"
```suggestion
                    properties = {DEBUG_ADDRESS = "host:not-a-number"},
                    expected = "Expected log address in DEBUG_ADDRESS to look like '<ip>|<host>[:<port>]'"
                    .. ", but got 'host:not-a-number' instead"
```

2022-03-29 05:06 UTC, kaklakariada commented on spec/AdapterProperties_spec.lua
> +                AdapterProperties.create({EXCLUDED_CAPABILITIES = "a,b,c"}):get_excluded_capabilities())
```suggestion
                AdapterProperties.create({EXCLUDED_CAPABILITIES = "a,b, c"}):get_excluded_capabilities())
```
also verify value with space

2022-03-29 05:22 UTC, redcatbear commented on .github/workflows/ci-build.yml
> +          busted --coverage
Actually I would like to keep this here, in case I change my mind on the global config. CI should always have coverage.

2022-03-30 11:19 UTC, kaklakariada approved these changes

2022-03-30 11:19 UTC, kaklakariada commented on virtual-schema-common-lua-0.1.0-1.rockspec
> +}
👍

2022-03-30 11:20 UTC, merged